[phases.setup]
nixPkgs = ["nodejs_20", "python312", "gcc", "gnumake"]
aptPkgs = ["libsqlite3-dev", "build-essential"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
